# Generated by Django 4.2.4 on 2023-08-16 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('birthdate', models.DateTimeField()),
                ('phonenum', models.CharField(max_length=100)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('pic', models.BinaryField(blank=True, null=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserHasAccidents',
            fields=[
                ('user_iduser', models.OneToOneField(db_column='user_iduser', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.user')),
            ],
            options={
                'db_table': 'user_has_accidents',
                'managed': False,
            },
        ),
    ]
