# Generated by Django 4.2.4 on 2023-08-15 13:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('idaccidents', models.AutoField(primary_key=True, serialize=False)),
                ('region', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'accidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('idguardian', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('phonenum', models.CharField(blank=True, max_length=45, null=True)),
                ('user_iduser', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guardian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lights',
            fields=[
                ('idlights', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'lights',
                'managed': False,
            },
        ),
    ]
